### ISSUE TITLE
sun.org.mozilla.javascript.internal.EvaluatorException: missing name after . operator 

### ISSUE THREAD

**Issue by kellyfj** [walterhiggins/ScriptCraft#167]
First time using CanaryMod and ScriptCraft

This was on Mac OSX 10.9.5 running Java 1.6.0_65

Using ScriptCraft dated 09-Nov-2014 13:29

```
[16:25:35] [CanaryMod] [INFO]: Starting: CanaryMod 1.7.10-1.1.2
[16:25:35] [CanaryMod] [INFO]: Canary Path: /Users/kellyfj/Desktop/server/CanaryMod.jar & Working From: /Users/kellyfj/Desktop/server
[16:25:35] [CanaryMod] [INFO]: Registered xml Database
[16:25:35] [CanaryMod] [INFO]: Found 1 plugins; total: 1
[16:25:35] [net.minecraft.server.dedicated.DedicatedServer] [INFO]: Starting minecraft server version 1.7.10
[16:25:35] [net.minecraft.server.dedicated.DedicatedServer] [INFO]: Loading properties
[16:25:35] [net.minecraft.server.dedicated.DedicatedServer] [INFO]: Generating keypair
[16:25:35] [net.minecraft.server.dedicated.DedicatedServer] [INFO]: Starting Minecraft server on *:25565
[16:25:35] [CanaryMod] [INFO]: Enabling Plugins...
[16:25:36] [org.scriptcraftjs.canarymod.ScriptCraftPlugin] [ERROR]: Error evaluating scriptcraft/lib/scriptcraft.js: Error: Error executing module events line #729 : Error evaluating module events-canary line #729 : javax.script.ScriptException: sun.org.mozilla.javascript.internal.EvaluatorException: missing name after . operator (<Unknown source>#45) in <Unknown source> at line number 45
 undefined
> undefined

> javax.script.ScriptException: sun.org.mozilla.javascript.internal.JavaScriptException: [object Error] (<Unknown source>#94) in <Unknown source> at line number 94
    at com.sun.script.javascript.RhinoScriptEngine.invoke(RhinoScriptEngine.java:230)
    at com.sun.script.javascript.RhinoScriptEngine.invokeFunction(RhinoScriptEngine.java:188)
    at org.scriptcraftjs.canarymod.ScriptCraftPlugin.enable(ScriptCraftPlugin.java:57)
    at net.canarymod.plugin.lifecycle.PluginLifecycleBase.enable(PluginLifecycleBase.java:30)
    at net.canarymod.plugin.lifecycle.JavaPluginLifecycle.enable(JavaPluginLifecycle.java:16)
    at net.canarymod.plugin.PluginManager.enablePlugin(PluginManager.java:70)
    at net.canarymod.plugin.PluginManager.enableAllPlugins(PluginManager.java:101)
    at net.canarymod.Canary.enablePlugins(Canary.java:284)
    at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:278)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:391)
    at net.minecraft.server.MinecraftServer$3.run(MinecraftServer.java:742)
```

FWIW trying this on Ubuntu (Zorin) Linux with the following Java version worked fine

```
administrator@Computer:~$ java -version
java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)
```

**Comment by ehur** [comment]
Hi Walter, trying to get minecraft/scriptcraft up and running on an upgraded Fedora environment, and I'm getting the error reported above; I have:

Fedora 21 running java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
CanaryMod-1.7.10-1.1.3.jar
downloaded latest scriptcraft.jar from http://scriptcraftjs.org/download/latest (today, Jan 2 at 13:23 pacific time)

still getting:
[13:16:57] [org.scriptcraftjs.canarymod.ScriptCraftPlugin] [ERROR]: Error evaluating scriptcraft/lib/scriptcraft.js: Error: Error executing module events line #729 : Error evaluating module events-canary line #729 : javax.script.ScriptException: sun.org.mozilla.javascript.internal.EvaluatorException: missing name after . operator (<Unknown source>#45) in <Unknown source> at line number 45
 undefined
> undefined

javax.script.ScriptException: sun.org.mozilla.javascript.internal.JavaScriptException: Error: Error executing module events line #729 : Error evaluating module events-canary line #729 : javax.script.ScriptException: sun.org.mozilla.javascript.internal.EvaluatorException: missing name after . operator (<Unknown source>#45) in <Unknown source> at line number 45
 undefined
> undefined
 (<Unknown source>#95) in <Unknown source> at line number 95
	at com.sun.script.javascript.RhinoScriptEngine.invoke(RhinoScriptEngine.java:300)
	at com.sun.script.javascript.RhinoScriptEngine.invokeFunction(RhinoScriptEngine.java:258)
	at org.scriptcraftjs.canarymod.ScriptCraftPlugin.enable(ScriptCraftPlugin.java:57)
	at net.canarymod.plugin.lifecycle.PluginLifecycleBase.enable(PluginLifecycleBase.java:30)
	at net.canarymod.plugin.lifecycle.JavaPluginLifecycle.enable(JavaPluginLifecycle.java:16)
	at net.canarymod.plugin.PluginManager.enablePlugin(PluginManager.java:71)
	at net.canarymod.plugin.PluginManager.enableAllPlugins(PluginManager.java:102)
	at net.canarymod.Canary.enablePlugins(Canary.java:284)

Can I verify the version of the scriptcraft.jar that I have? When I open it up and look in the manifest file, all I see is:
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.9.3
Created-By: 1.8.0_20-b26 (Oracle Corporation)

**Comment by ehur** [comment]
Version 3.0.3 of scriptcraft works for me (after I remembered to clear out the contents of the scriptcraft folder under the canaryMod install location. the problem persisted until I did that - the existing files were not overwritten when the jar exploded.)

**Comment by walterhiggins** [comment]
Hi @ehur 
Yeah. There may have been an issue with file timestamps. I'm glad that fixed the problem for you.
