### ISSUE TITLE
/js oak() returns ClassNotFoundException

### ISSUE THREAD

**Issue by kellyfj** [walterhiggins/ScriptCraft#177]
I am using 
```Dec 21 14:22 CanaryMod-1.7.10-1.1.2.jar```
and latest ScriptCraft
```	scriptcraft.jar	14-Nov-2014 21:38	138K	 ```

Tried to create a tree as per https://github.com/walterhiggins/ScriptCraft/blob/master/docs/API-Reference.md#drone-trees-methods

I tried

```/js oak();```
and
```/js up().oak();```

and got the following

```
> javax.script.ScriptException: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.bukkit.Location in <eval> at line number 622 at column number 8
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:586)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:511)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:227)
	at org.scriptcraftjs.canarymod.ScriptCraftPlugin.executeCommand(ScriptCraftPlugin.java:102)
	at org.scriptcraftjs.canarymod.ScriptCraftPlugin.jsCommand(ScriptCraftPlugin.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.canarymod.commandsys.CommandManager$1.execute(CommandManager.java:313)
	at net.canarymod.commandsys.CanaryCommand.parseCommand(CanaryCommand.java:97)
	at net.canarymod.commandsys.CommandManager.parseCommand(CommandManager.java:176)
	at net.canarymod.api.entity.living.humanoid.CanaryPlayer.executeCommand(CanaryPlayer.java:256)
	at net.canarymod.api.entity.living.humanoid.CanaryPlayer.chat(CanaryPlayer.java:129)
	at net.minecraft.network.NetHandlerPlayServer.a(NetHandlerPlayServer.java:665)
	at net.minecraft.network.play.client.C01PacketChatMessage.a(C01PacketChatMessage.java:36)
	at net.minecraft.network.play.client.C01PacketChatMessage.a(C01PacketChatMessage.java:48)
	at net.minecraft.network.NetworkManager.a(NetworkManager.java:174)
	at net.minecraft.network.NetworkSystem.c(NetworkSystem.java:108)
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:622)
	at net.minecraft.server.dedicated.DedicatedServer.v(DedicatedServer.java:365)
	at net.minecraft.server.MinecraftServer.u(MinecraftServer.java:526)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:430)
	at net.minecraft.server.MinecraftServer$3.run(MinecraftServer.java:742)
Caused by: <eval>:622:8 java.lang.RuntimeException: java.lang.ClassNotFoundException: org.bukkit.Location
	at jdk.nashorn.internal.runtime.ECMAException.create(ECMAException.java:111)
	at jdk.nashorn.internal.scripts.Script$\^eval\_.__onEnable$__onCommand(<eval>:622)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:526)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:209)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:378)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:185)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:505)
	... 22 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.bukkit.Location
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:382)
	at jdk.nashorn.internal.objects.NativeFunction.apply(NativeFunction.java:130)
	at jdk.nashorn.internal.scripts.Script$\^eval\_.L:1$L:746$L:755(<eval>:761)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:526)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:209)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:378)
	at jdk.nashorn.internal.objects.NativeFunction.apply(NativeFunction.java:130)
	at jdk.nashorn.internal.scripts.Script$\^eval\_.L:1$L:746$L:766(<eval>:768)
	at jdk.nashorn.internal.scripts.Script$\^eval\_.runScript(<eval>:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:535)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:209)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:378)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:568)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:525)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:521)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:192)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at jdk.nashorn.internal.scripts.Script$\^eval\_.__onEnable$__onCommand(<eval>:597)
	... 27 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.Location
	at jdk.nashorn.internal.runtime.NativeJavaPackage.classNotFound(NativeJavaPackage.java:158)
	at jdk.nashorn.internal.scripts.Script$\^eval\_$2.L:1$L:1835$L:1836(<eval>:1841)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:535)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:209)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:378)
	... 44 more
```

**Comment by walterhiggins** [comment]
This fix only works in CanaryMod 1.2 (Minecraft 1.8). No further development is being done on CanaryMod 1.1.X by the CanaryMod team.

https://github.com/CanaryModTeam/CanaryMod/issues/154
