### ISSUE TITLE
No such function __onCommand

### ISSUE THREAD

**Issue by d0m-live** [walterhiggins/ScriptCraft#179]
Trying to help a young kid get started with JavaScript.  First time I tried CraftBukkit wasn't available.  Now that it is I am getting an error "No such function __onCommand"

Using:
  MineCraft 1.8.1
  CraftBukkit 1.8 (Compiled using Git Bash 1.9.5 and JDK 8 u 25)
  Windows Technical Preview Build 9879 64bit on MacBook Pro A1398 using BootCamp 5.1
  ScriptCraft (version in folder /download/2014-11/20141114-v3.0.1)

Thanks for all your work with this,
ConstructShaft

See Server Log:

C:\Users\Mac\Downloads\test>java -Xmx1024M -jar craftbukkit-1.8.jar -o true
Loading libraries, please wait...
[04:08:28 INFO]: Starting minecraft server version 1.8
[04:08:28 INFO]: Loading properties
[04:08:28 INFO]: Default game type: SURVIVAL
[04:08:28 INFO]: Generating keypair
[04:08:28 INFO]: Starting Minecraft server on *:25565
[04:08:29 INFO]: This server is running CraftBukkit version git-Bukkit-81ab957 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
[04:08:29 INFO]: [scriptcraft] Loading scriptcraft v3.0.1-2014-11-14
[04:08:29 INFO]: Preparing level "world"
[04:08:29 INFO]: Converting map!
[04:08:29 INFO]: Scanning folders...
[04:08:29 INFO]: Total conversion count is 0
[04:08:29 INFO]: Preparing start region for level 0 (Seed: -3926028877287343380)
[04:08:29 INFO]: Preparing start region for level 1 (Seed: -3926028877287343380)
[04:08:30 INFO](Done): Preparing start region for level 2 (Seed: -3926028877287343380)
[04:08:30 INFO](Done): [scriptcraft] Enabling scriptcraft v3.0.1-2014-11-14
[04:08:30 WARN]: javax.script.ScriptException: TypeError: Cannot read property "info" from undefined in <eval> at line number 70
[04:08:30 WARN]:        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:586)
[04:08:30 WARN]:        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:511)
[04:08:30 WARN]:        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:227)
[04:08:30 WARN]:        at org.scriptcraftjs.bukkit.ScriptCraftPlugin.onEnable(ScriptCraftPlugin.java:38)
[04:08:30 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[04:08:30 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327)
[04:08:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[04:08:30 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:340)
[04:08:30 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:312)
[04:08:30 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:394)
[04:08:30 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:362)
[04:08:30 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:317)
[04:08:30 WARN]:        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:190)
[04:08:30 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:473)
[04:08:30 WARN]:        at java.lang.Thread.run(Unknown Source)
[04:08:30 WARN]: Caused by: <eval>:70 TypeError: Cannot read property "info" from undefined
[04:08:30 WARN]:        at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:58)
[04:08:30 WARN]:        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:214)
[04:08:30 WARN]:        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:186)
[04:08:30 WARN]:        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:173)
[04:08:30 WARN]:        at jdk.nashorn.internal.runtime.Undefined.lookupTypeError(Undefined.java:128)
[04:08:30 WARN]:        at jdk.nashorn.internal.runtime.Undefined.lookup(Undefined.java:113)
[04:08:30 WARN]:        at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:98)
[04:08:30 WARN]:        at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176)
[04:08:30 WARN]:        at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
[04:08:30 WARN]:        at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:144)
[04:08:30 WARN]:        at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:232)
[04:08:30 WARN]:        at jdk.nashorn.internal.scripts.Script$^eval_.L:5$L:60(<eval>:70)
[04:08:30 WARN]:        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:541)
[04:08:30 WARN]:        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:209)
[04:08:30 WARN]:        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:378)
[04:08:30 WARN]:        at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:185)
[04:08:30 WARN]:        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:505)
[04:08:30 WARN]:        ... 13 more
[04:08:30 ERROR]: [scriptcraft] TypeError: Cannot read property "info" from undefined in <eval> at line number 70
[04:08:30 INFO](Done): Server permissions file permissions.yml is empty, ignoring it

[04:09:03 INFO]: UUID of player constructshaft is dffa553a-8847-4e99-87ca-829df6cb8c55
[04:09:03 INFO]: constructshaft[/127.0.0.1:59622] logged in with entity id 163 at ([world] 71.40904590751106, 58.0, 16.88712294964218)
[04:09:14 INFO]: constructshaft issued server command: /js 1+1
[04:09:14 ERROR]: [scriptcraft] java.lang.NoSuchMethodException: No such function __onCommand
[04:09:14 WARN]: java.lang.NoSuchMethodException: No such function __onCommand
[04:09:14 WARN]:        at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:190)
[04:09:14 WARN]:        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:505)
[04:09:14 WARN]:        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:227)
[04:09:14 WARN]:        at org.scriptcraftjs.bukkit.ScriptCraftPlugin.onCommand(ScriptCraftPlugin.java:76)
[04:09:14 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[04:09:14 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[04:09:14 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:624)
[04:09:14 WARN]:        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1058)
[04:09:14 WARN]:        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:919)
[04:09:14 WARN]:        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:37)
[04:09:14 WARN]:        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:9)
[04:09:14 WARN]:        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[04:09:14 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[04:09:14 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[04:09:14 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:643)
[04:09:14 WARN]:        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284)
[04:09:14 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:598)
[04:09:14 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:506)
[04:09:14 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by AdrianKusmierek** [comment]
I have the same problem in 2019.

**Comment by jwulf** [comment]
What version and flavor of Minecraft server?

**Comment by toivoh** [comment]
I got similar symptoms (`No such function __onCommand`, `No such function __onTabComplete`), but that was because the installation instructions at https://github.com/walterhiggins/ScriptCraft/blob/master/README.md pointed me to download `scriptcraft.jar` from http://scriptcraftjs.org/download/latest, which contains a release from 2015.

When I deleted the `spigotmc/scriptcraft` directory, and used `scriptcraft.jar` from https://github.com/walterhiggins/ScriptCraft/releases/tag/3.4.0 instead, everything worked fine.
