### ISSUE TITLE
Error using box command

### ISSUE THREAD

**Issue by slooker** [walterhiggins/ScriptCraft#254]
I'm using Spigot 1.8.6 and mcMMO 1.5.03 and ScriptCraft (Whatever version I downloaded yesterday from your main website.)

[18:12:33 INFO]: slooker issued server command: /js box(5.0)
[18:12:33 ERROR]: [scriptcraft] Error while trying to evaluate javascript: box(5.0), Error: JavaException: javax.script.ScriptException: sun.org.mozilla.javascript.internal.EvaluatorException: The choice of Java constructor getTargetBlock matching JavaScript argument types (null,number) is ambiguous; candidate constructors are:
    interface org.bukkit.block.Block getTargetBlock(java.util.HashSet,int)
    interface org.bukkit.block.Block getTargetBlock(java.util.Set,int) (<Unknown source>#303) in <Unknown source> at line number 303
[18:12:33 ERROR]: [scriptcraft] javax.script.ScriptException: sun.org.mozilla.javascript.internal.JavaScriptException: [object Error] (<Unknown source>#630) in <Unknown source> at line number 630
[18:12:33 WARN]: javax.script.ScriptException: sun.org.mozilla.javascript.internal.JavaScriptException: [object Error] (<Unknown source>#630) in <Unknown source> at line number 630
[18:12:33 WARN]:   at com.sun.script.javascript.RhinoScriptEngine.invoke(RhinoScriptEngine.java:230)
[18:12:33 WARN]:   at com.sun.script.javascript.RhinoScriptEngine.invokeFunction(RhinoScriptEngine.java:188)
[18:12:33 WARN]:   at org.scriptcraftjs.bukkit.ScriptCraftPlugin.onCommand(ScriptCraftPlugin.java:76)
[18:12:33 WARN]:   at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[18:12:33 WARN]:   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[18:12:33 WARN]:   at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642)
[18:12:33 WARN]:   at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135)
[18:12:33 WARN]:   at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970)
[18:12:33 WARN]:   at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[18:12:33 WARN]:   at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[18:12:33 WARN]:   at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[18:12:33 WARN]:   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
[18:12:33 WARN]:   at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
[18:12:33 WARN]:   at java.util.concurrent.FutureTask.run(FutureTask.java:138)
[18:12:33 WARN]:   at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19)
[18:12:33 WARN]:   at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718)
[18:12:33 WARN]:   at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367)
[18:12:33 WARN]:   at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
[18:12:33 WARN]:   at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
[18:12:33 WARN]:   at java.lang.Thread.run(Thread.java:695)
[18:12:37 INFO]: slooker issued server command: /js box(blocks.oak)
[18:12:37 ERROR]: [scriptcraft] Error while trying to evaluate javascript: box(blocks.oak), Error: JavaException: javax.script.ScriptException: sun.org.mozilla.javascript.internal.EvaluatorException: The choice of Java constructor getTargetBlock matching JavaScript argument types (null,number) is ambiguous; candidate constructors are:
    interface org.bukkit.block.Block getTargetBlock(java.util.HashSet,int)
    interface org.bukkit.block.Block getTargetBlock(java.util.Set,int) (<Unknown source>#303) in <Unknown source> at line number 303
[18:12:37 ERROR]: [scriptcraft] javax.script.ScriptException: sun.org.mozilla.javascript.internal.JavaScriptException: [object Error] (<Unknown source>#630) in <Unknown source> at line number 630
[18:12:37 WARN]: javax.script.ScriptException: sun.org.mozilla.javascript.internal.JavaScriptException: [object Error] (<Unknown source>#630) in <Unknown source> at line number 630
[18:12:37 WARN]:   at com.sun.script.javascript.RhinoScriptEngine.invoke(RhinoScriptEngine.java:230)
[18:12:37 WARN]:   at com.sun.script.javascript.RhinoScriptEngine.invokeFunction(RhinoScriptEngine.java:188)
[18:12:37 WARN]:   at org.scriptcraftjs.bukkit.ScriptCraftPlugin.onCommand(ScriptCraftPlugin.java:76)
[18:12:37 WARN]:   at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[18:12:37 WARN]:   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[18:12:37 WARN]:   at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642)
[18:12:37 WARN]:   at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135)
[18:12:37 WARN]:   at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970)
[18:12:37 WARN]:   at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[18:12:37 WARN]:   at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[18:12:37 WARN]:   at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[18:12:37 WARN]:   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
[18:12:37 WARN]:   at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
[18:12:37 WARN]:   at java.util.concurrent.FutureTask.run(FutureTask.java:138)
[18:12:37 WARN]:   at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19)
[18:12:37 WARN]:   at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718)
[18:12:37 WARN]:   at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367)
[18:12:37 WARN]:   at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
[18:12:37 WARN]:   at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
[18:12:37 WARN]:   at java.lang.Thread.run(Thread.java:695)

**Comment by walterhiggins** [comment]
Will be fixed in release 3.1.8
